@Library('roboshop-shared-library') _

env.REPONAME ="user"
env.TFDIR="mutable-infra"
backendinfra()

//  pipeline {
//     agent { label 'WS' }
//     options {
//         ansiColor('xterm')
//     }
    
//      parameters {
//         choice(name: 'ENV', choices: ['dev', 'prod'], description: 'Select the Environment')
//         choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Create or Destroy')
//     }
  
  
//  stages {
                 
//         stage('terraform init'){
//              steps {
//                 sh "git branch: 'main', url: 'https://github.com/jogendra-b54/cart.git' "
//                 sh "cd mutable-infra"
//                 sh "ls -ltr"
//                 sh "pwd"
//                 sh "terrafile -f env-${ENV}/Terrafile"
//                 sh "terraform init -backend-config=env-${ENV}/${ENV}-backend.tfvars"
//              }
//         }
//         stage('terraform plan'){
//              steps {
//                 sh "terraform plan -var-file=env-${ENV}/${ENV}.tfvars"
//              }
//         }
//         stage('terraform apply'){
//              steps {
//                 sh "terraform ${ACTION} -auto-approve -var-file=env-${ENV}/${ENV}.tfvars"
//              }
//         }
//     }
//  }